version: '2'

services:
  cloudbees_dse_workspace:
    container_name: cloudbees_dse_workspace
    build:
      context: .
    image: cloudbees/dse-workspace:local
    ports:
      - "50000:50000"
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./.m2:/root/.m2
      - ./bin:/root/bin
      - ./insights:/root/insights
      - ./shinobi-tools:/root/shinobi-tools
      - ./support:/root/support
